### PR TITLE
Xenial base + Mono 4.4.2.11

### PR DESCRIPTION
**Pull request by CL0SeY**
Updated the base OS + Mono version.

Attempted to inherit from either microsoft/dotnet or library/mono but still experienced issues.

@seiggy you might be interested in testing?

### CODE REVIEW

**Comment by seiggy** [comment]
Sure thing. I'll give it a shot on Monday when I'm back in the office.

**Comment by CL0SeY** [comment]
FYI I've found some other problems with the "dotnet" cli which doesn't seem to include all the things required for mono. So there's the libuv thing, but also an issue with mono looking for libSystemNative.so

I've got this working in one of my images by doing this, not sure if you've gotten around it another way:

```
RUN ln -s /usr/share/dotnet/shared/Microsoft.NETCore.App/1.0.0/System.Native.so /app/bin/Release/net451/ubuntu.16.04-x64/publish/libSystem.Native.so
```

**Comment by CL0SeY** [comment]
I've updated the dockerfile to symlink System.Native.so to libSystem.Native.so , and to remove the libuv.so symlink as it doesn't seem to be required.

**Comment by CL0SeY** [comment]
See #3 instead.

**Pull request closed without merging**
