### PR TITLE
Use microsoft/dotnet as libjpeg62 is added for debian compat.

### PR DESCRIPTION
**Pull request by CL0SeY**
Reduce a bunch of tech debt by inheriting from the microsoft/dotnet image. Turns out it was pretty easy fix the libjpeg62 dependency.

@seiggy can you try this one instead. Cheers.

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
Why did you end up removing changing `binutils mono-devel ca-certificates-mono fsharp mono-vbnc nuget referenceassemblies-pcl` to just `mono-devel` ?  This limits a lot what you can do if you're trying to compile things related to vb,f#,or pcl.

**Comment by CL0SeY** [comment]
Hey,

Thanks for the feedback!

I think I must have been putting my containers on a diet at the time, trying to reduce their sizes. I'll have a look and see what impact putting those packages back in has.

Are those packages only required for building, or also needed for running those types of solutions?

**Comment by TheAngryByrd** [comment]
For running I don't think they're needed but they're needed for compile time. Maybe it's a good idea to have one for compiling and one for running. 
- fsharp is needed for compiling fsprojs 
- vbnc according to this is needed for compiling vb:  http://www.mono-project.com/docs/about-mono/languages/visualbasic/ 
- Depending on if you're dealing with PCLs referenceassemblies-pcl might be needed according to http://www.mono-project.com/docs/getting-started/install/linux/
- ca-certificates-mono and nuget go more hand in hand, you'll get SSL verification failures if you don't have mono's cert store updated.

**Comment by CL0SeY** [comment]
Cool sounds good. I was thinking of splitting it up as well :)

**Pull request merged**
